# Generated by Django 5.2.13 on 2026-04-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_latitude_alter_place_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='place_images/', verbose_name='Изображение'),
        ),
    ]
