# Generated by Django 5.2.13 on 2026-04-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_placeimage_place'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['order'], name='places_plac_order_66e296_idx'),
        ),
    ]
